# Dividend based investing  @Mayank_Srivastav

In [1]:
import pandas as pd
import numpy as np
import yfinance as yf
import math
from scipy import stats

In [2]:
tickers = pd.read_csv('top_50_indian_stocks.csv')
tickers.head()

         Ticker               Company Name
0   RELIANCE.NS        Reliance Industries
1        TCS.NS  Tata Consultancy Services
2   HDFCBANK.NS                  HDFC Bank
3       INFY.NS                    Infosys
4  ICICIBANK.NS                 ICICI Bank

Weighted Scoring Model for finding the final score

In [9]:
def create_dividend_df(tickers):
    columns = [
        "Ticker", 
        "Dividend Yield(%)", 
        "Dividend Rate",
        "Payout Ratio(%)", 
        "5 Year Avg Dividend Yield(%)", 
        "Earning Growth(%)"
        
    ]
    
    dividend_df = pd.DataFrame(columns=columns)
    
    for stock in tickers:
        ticker = yf.Ticker(stock)
        info = ticker.info 
        
        dividend_yield = info.get("dividendYield", np.nan) * 100 if info.get("dividendYield") else np.nan
        dividend_rate = info.get("dividendRate", np.nan) 
        payout_ratio = info.get("payoutRatio", np.nan) * 100 if info.get("payoutRatio") else np.nan
        five_year_avg_dividend_yield = info.get("fiveYearAvgDividendYield", np.nan) * 100 if info.get("fiveYearAvgDividendYield") else np.nan
        earning_growth = info.get("earningsGrowth", np.nan) * 100 if info.get("earningsGrowth") else np.nan
        
        dividend_df.loc[len(dividend_df)] = [stock, dividend_yield, dividend_rate, payout_ratio, five_year_avg_dividend_yield, earning_growth]
        
    
    numeric_cols = [
          "Dividend Yield(%)", 
        "Dividend Rate",
        "Payout Ratio(%)", 
        "5 Year Avg Dividend Yield(%)", 
        "Earning Growth(%)"
    ]
    

    for col in numeric_cols:
        if col == "Payout Ratio":
            dividend_df[col+ " Normalised"] = 1 - ((dividend_df[col] - dividend_df[col].min()) / (dividend_df[col].max() - dividend_df[col].min()))
        else:
            dividend_df[col+ " Normalised"] = (dividend_df[col] - dividend_df[col].min()) / (dividend_df[col].max() - dividend_df[col].min())
        
    return dividend_df

In [4]:
tickers_list = tickers["Ticker"].values.tolist()
dividend_df = create_dividend_df(tickers_list)
dividend_df

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}

,Ticker,Dividend Yield(%),Dividend Rate,Payout Ratio(%),5 Year Avg Dividend Yield(%),Earning Growth(%),Dividend Yield(%) Normalised,Dividend Rate Normalised,Payout Ratio(%) Normalised,5 Year Avg Dividend Yield(%) Normalised,Earning Growth(%) Normalised
0,RELIANCE.NS,46.0,6.0,9.21,44.0,-12.6,0.043433,0.034483,0.085562,0.047146,0.068275
1,TCS.NS,592.0,124.0,46.32,149.0,12.2,0.608066,0.774295,0.48098,0.177419,0.09128
2,HDFCBANK.NS,163.0,13.0,21.76,102.0,7.5,0.164426,0.07837,0.219286,0.119107,0.08692
3,INFY.NS,480.0,50.0,64.65,240.0,11.8,0.492244,0.310345,0.676292,0.290323,0.090909
4,ICICIBANK.NS,79.0,11.0,14.71,99.0,8.4,0.077559,0.065831,0.144166,0.115385,0.087755
5,HINDUNILVR.NS,202.0,44.0,95.03,158.0,21.4,0.204757,0.272727,1.0,0.188586,0.099814
6,SBIN.NS,166.0,17.35,17.44,150.0,-3.1,0.167528,0.105643,0.173255,0.17866,0.077087
7,BAJFINANCE.NS,55.0,5.4,14.42,24.0,21.4,0.05274,0.030721,0.141076,0.022333,0.099814
8,BHARTIARTL.NS,86.0,16.0,36.060002,80.0,-34.0,0.084798,0.097179,0.371657,0.091811,0.048423
9,ITC.NS,552.0,16.0,86.92,372.0,-72.7,0.566701,0.097179,0.913586,0.454094,0.012523
10,KOTAKBANK.NS,12.0,0.5,2.58,6.0,9.8,0.008273,0.0,0.014917,0.0,0.089054
11,ADANIENT.NS,4.0,1.3,1.71,65.0,NaN,0.0,0.005016,0.005647,0.073201,NaN
12,LT.NS,90.0,38.0,29.09,91.0,-34.5,0.088935,0.23511,0.297389,0.105459,0.047959
13,HCLTECH.NS,872.0,96.0,88.01,357.0,-0.2,0.897622,0.598746,0.9252,0.435484,0.079777
14,ASIANPAINT.NS,104.0,27.5,55.53,87.0,69.2,0.103413,0.169279,0.579116,0.100496,0.144156
15,AXISBANK.NS,7.0,1.0,1.18,103.0,6.4,0.003102,0.003135,0.0,0.120347,0.0859
16,SUNPHARMA.NS,86.0,16.0,34.52,93.0,25.6,0.084798,0.097179,0.355248,0.10794,0.103711
17,WIPRO.NS,971.0,17.0,87.58,151.0,-1.6,1.0,0.103448,0.920618,0.179901,0.078479
18,ULTRACEMCO.NS,67.0,77.5,27.93,53.0,45.3,0.06515,0.482759,0.285029,0.058313,0.121985
19,HDFCLIFE.NS,36.0,2.1,23.7,31.0,4.1,0.033092,0.010031,0.239957,0.031017,0.083766
20,ONGC.NS,794.0,18.5,41.0,511.0,47.8,0.81696,0.112853,0.424294,0.626551,0.124304
21,NTPC.NS,322.0,11.35,29.07,336.0,-1.6,0.328852,0.068025,0.297176,0.409429,0.078479
22,POWERGRID.NS,431.0,12.25,44.75,474.0,9.6,0.441572,0.073668,0.464251,0.580645,0.088868
23,TATAMOTORS.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,INDUSINDBK.NS,16.0,1.5,NaN,54.0,NaN,0.01241,0.00627,NaN,0.059553,NaN
25,ADANIGREEN.NS,NaN,NaN,NaN,NaN,209.8,NaN,NaN,NaN,NaN,0.274583
26,TITAN.NS,26.0,11.0,19.229999,27.0,35.1,0.022751,0.065831,0.192328,0.026055,0.112523
27,DIVISLAB.NS,45.0,30.0,31.01,114.0,13.6,0.042399,0.184953,0.317848,0.133995,0.092579
28,TECHM.NS,355.0,51.0,83.04,232.0,15.8,0.362978,0.316614,0.872243,0.280397,0.09462
29,MARUTI.NS,102.0,140.0,28.91,80.0,-6.4,0.101344,0.874608,0.295471,0.091811,0.074026
30,COALINDIA.NS,505.0,22.0,52.32,812.0,12.9,0.518097,0.134796,0.544912,1.0,0.091929
31,BPCL.NS,646.0,20.0,37.2,540.0,28.0,0.663909,0.122257,0.383804,0.662531,0.105937
32,JSWSTEEL.NS,58.0,7.1,3.07,98.0,991.8,0.055843,0.041379,0.020139,0.114144,1.0
33,DRREDDY.NS,59.0,8.0,15.560001,63.0,-86.2,0.056877,0.047022,0.153223,0.07072,0.0
34,BAJAJFINSV.NS,7.0,1.3,1.64,14.0,5.7,0.003102,0.005016,0.004901,0.009926,0.08525
35,ADANIPORTS.NS,42.0,7.5,12.020001,57.0,3.6,0.039297,0.043887,0.115503,0.063275,0.083302
36,CIPLA.NS,90.0,13.0,27.08,48.0,-54.6,0.088935,0.07837,0.275972,0.052109,0.029314
37,BRITANNIA.NS,173.0,90.5,71.309996,172.0,21.1,0.174767,0.564263,0.747256,0.205955,0.099536
38,HAVELLS.NS,102.0,12.0,37.12,59.0,39.6,0.101344,0.0721,0.382952,0.065757,0.116698
39,SHREECEM.NS,62.0,160.0,28.97,33.0,3.4,0.059979,1.0,0.296111,0.033499,0.083117
40,GRASIM.NS,32.0,10.0,13.67,36.0,60.8,0.028956,0.059561,0.133085,0.037221,0.136364
41,TATASTEEL.NS,212.0,4.0,41.619998,280.0,125.2,0.215098,0.021944,0.4309,0.33995,0.196104
42,HEROMOTOCO.NS,306.0,150.0,61.04,313.0,25.7,0.312306,0.937304,0.637826,0.380893,0.103803
43,M&M.NS,104.0,33.0,16.63,86.0,44.8,0.103413,0.203762,0.164624,0.099256,0.121521
44,EICHERMOT.NS,92.0,70.0,34.87,45.0,11.5,0.091003,0.435737,0.358977,0.048387,0.090631
45,IOC.NS,695.0,10.0,32.709998,669.0,78.1,0.714581,0.059561,0.335962,0.822581,0.152412
46,SBICARD.NS,40.0,2.5,10.98,NaN,13.9,0.037229,0.012539,0.104422,NaN,0.092857
47,PIDILITIND.NS,72.0,11.5,41.65,51.0,37.0,0.070321,0.068966,0.43122,0.055831,0.114286
48,DMART.NS,NaN,NaN,NaN,NaN,19.6,NaN,NaN,NaN,NaN,0.098145
49,HDFCAMC.NS,204.0,54.0,67.67,171.0,-2.8,0.206825,0.335423,0.708471,0.204715,0.077365

In [5]:
weights = {
        "Dividend Yield(%) Normalised": 0.3,
        "Dividend Rate Normalised": 0.2,
        "Payout Ratio(%) Normalised": 0.2,
        "5 Year Avg Dividend Yield(%) Normalised": 0.2,
        "Earning Growth(%) Normalised": 0.1
    }

dividend_df["Dividend Score"] = dividend_df[[col for col in weights.keys()]].mul(list(weights.values())).sum(axis = 1)
dividend_df

,Ticker,Dividend Yield(%),Dividend Rate,Payout Ratio(%),5 Year Avg Dividend Yield(%),Earning Growth(%),Dividend Yield(%) Normalised,Dividend Rate Normalised,Payout Ratio(%) Normalised,5 Year Avg Dividend Yield(%) Normalised,Earning Growth(%) Normalised,Dividend Score
0,RELIANCE.NS,46.0,6.0,9.21,44.0,-12.6,0.043433,0.034483,0.085562,0.047146,0.068275,0.053296
1,TCS.NS,592.0,124.0,46.32,149.0,12.2,0.608066,0.774295,0.48098,0.177419,0.09128,0.478087
2,HDFCBANK.NS,163.0,13.0,21.76,102.0,7.5,0.164426,0.07837,0.219286,0.119107,0.08692,0.141372
3,INFY.NS,480.0,50.0,64.65,240.0,11.8,0.492244,0.310345,0.676292,0.290323,0.090909,0.412156
4,ICICIBANK.NS,79.0,11.0,14.71,99.0,8.4,0.077559,0.065831,0.144166,0.115385,0.087755,0.09712
5,HINDUNILVR.NS,202.0,44.0,95.03,158.0,21.4,0.204757,0.272727,1.0,0.188586,0.099814,0.363671
6,SBIN.NS,166.0,17.35,17.44,150.0,-3.1,0.167528,0.105643,0.173255,0.17866,0.077087,0.149479
7,BAJFINANCE.NS,55.0,5.4,14.42,24.0,21.4,0.05274,0.030721,0.141076,0.022333,0.099814,0.06463
8,BHARTIARTL.NS,86.0,16.0,36.060002,80.0,-34.0,0.084798,0.097179,0.371657,0.091811,0.048423,0.142411
9,ITC.NS,552.0,16.0,86.92,372.0,-72.7,0.566701,0.097179,0.913586,0.454094,0.012523,0.464234
10,KOTAKBANK.NS,12.0,0.5,2.58,6.0,9.8,0.008273,0.0,0.014917,0.0,0.089054,0.014371
11,ADANIENT.NS,4.0,1.3,1.71,65.0,NaN,0.0,0.005016,0.005647,0.073201,NaN,0.016773
12,LT.NS,90.0,38.0,29.09,91.0,-34.5,0.088935,0.23511,0.297389,0.105459,0.047959,0.159068
13,HCLTECH.NS,872.0,96.0,88.01,357.0,-0.2,0.897622,0.598746,0.9252,0.435484,0.079777,0.66915
14,ASIANPAINT.NS,104.0,27.5,55.53,87.0,69.2,0.103413,0.169279,0.579116,0.100496,0.144156,0.215218
15,AXISBANK.NS,7.0,1.0,1.18,103.0,6.4,0.003102,0.003135,0.0,0.120347,0.0859,0.034217
16,SUNPHARMA.NS,86.0,16.0,34.52,93.0,25.6,0.084798,0.097179,0.355248,0.10794,0.103711,0.147884
17,WIPRO.NS,971.0,17.0,87.58,151.0,-1.6,1.0,0.103448,0.920618,0.179901,0.078479,0.548641
18,ULTRACEMCO.NS,67.0,77.5,27.93,53.0,45.3,0.06515,0.482759,0.285029,0.058313,0.121985,0.196964
19,HDFCLIFE.NS,36.0,2.1,23.7,31.0,4.1,0.033092,0.010031,0.239957,0.031017,0.083766,0.074505
20,ONGC.NS,794.0,18.5,41.0,511.0,47.8,0.81696,0.112853,0.424294,0.626551,0.124304,0.490258
21,NTPC.NS,322.0,11.35,29.07,336.0,-1.6,0.328852,0.068025,0.297176,0.409429,0.078479,0.26143
22,POWERGRID.NS,431.0,12.25,44.75,474.0,9.6,0.441572,0.073668,0.464251,0.580645,0.088868,0.365071
23,TATAMOTORS.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
24,INDUSINDBK.NS,16.0,1.5,NaN,54.0,NaN,0.01241,0.00627,NaN,0.059553,NaN,0.016887
25,ADANIGREEN.NS,NaN,NaN,NaN,NaN,209.8,NaN,NaN,NaN,NaN,0.274583,0.027458
26,TITAN.NS,26.0,11.0,19.229999,27.0,35.1,0.022751,0.065831,0.192328,0.026055,0.112523,0.07492
27,DIVISLAB.NS,45.0,30.0,31.01,114.0,13.6,0.042399,0.184953,0.317848,0.133995,0.092579,0.149337
28,TECHM.NS,355.0,51.0,83.04,232.0,15.8,0.362978,0.316614,0.872243,0.280397,0.09462,0.412206
29,MARUTI.NS,102.0,140.0,28.91,80.0,-6.4,0.101344,0.874608,0.295471,0.091811,0.074026,0.290184
30,COALINDIA.NS,505.0,22.0,52.32,812.0,12.9,0.518097,0.134796,0.544912,1.0,0.091929,0.500564
31,BPCL.NS,646.0,20.0,37.2,540.0,28.0,0.663909,0.122257,0.383804,0.662531,0.105937,0.443485
32,JSWSTEEL.NS,58.0,7.1,3.07,98.0,991.8,0.055843,0.041379,0.020139,0.114144,1.0,0.151885
33,DRREDDY.NS,59.0,8.0,15.560001,63.0,-86.2,0.056877,0.047022,0.153223,0.07072,0.0,0.071256
34,BAJAJFINSV.NS,7.0,1.3,1.64,14.0,5.7,0.003102,0.005016,0.004901,0.009926,0.08525,0.013424
35,ADANIPORTS.NS,42.0,7.5,12.020001,57.0,3.6,0.039297,0.043887,0.115503,0.063275,0.083302,0.064652
36,CIPLA.NS,90.0,13.0,27.08,48.0,-54.6,0.088935,0.07837,0.275972,0.052109,0.029314,0.110902
37,BRITANNIA.NS,173.0,90.5,71.309996,172.0,21.1,0.174767,0.564263,0.747256,0.205955,0.099536,0.365879
38,HAVELLS.NS,102.0,12.0,37.12,59.0,39.6,0.101344,0.0721,0.382952,0.065757,0.116698,0.146235
39,SHREECEM.NS,62.0,160.0,28.97,33.0,3.4,0.059979,1.0,0.296111,0.033499,0.083117,0.292227
40,GRASIM.NS,32.0,10.0,13.67,36.0,60.8,0.028956,0.059561,0.133085,0.037221,0.136364,0.068296
41,TATASTEEL.NS,212.0,4.0,41.619998,280.0,125.2,0.215098,0.021944,0.4309,0.33995,0.196104,0.242699
42,HEROMOTOCO.NS,306.0,150.0,61.04,313.0,25.7,0.312306,0.937304,0.637826,0.380893,0.103803,0.495277
43,M&M.NS,104.0,33.0,16.63,86.0,44.8,0.103413,0.203762,0.164624,0.099256,0.121521,0.136704
44,EICHERMOT.NS,92.0,70.0,34.87,45.0,11.5,0.091003,0.435737,0.358977,0.048387,0.090631,0.204984
45,IOC.NS,695.0,10.0,32.709998,669.0,78.1,0.714581,0.059561,0.335962,0.822581,0.152412,0.473236
46,SBICARD.NS,40.0,2.5,10.98,NaN,13.9,0.037229,0.012539,0.104422,NaN,0.092857,0.043847
47,PIDILITIND.NS,72.0,11.5,41.65,51.0,37.0,0.070321,0.068966,0.43122,0.055831,0.114286,0.143728
48,DMART.NS,NaN,NaN,NaN,NaN,19.6,NaN,NaN,NaN,NaN,0.098145,0.009814
49,HDFCAMC.NS,204.0,54.0,67.67,171.0,-2.8,0.206825,0.335423,0.708471,0.204715,0.077365,0.319506

Sort according to Dividend score

In [ ]:
dividend_df = dividend_df[dividend_df["Dividend Yield(%)"] > 0].copy()

dividend_df = dividend_df.sort_values(by = "Dividend Score", ascending = False)
dividend_df.head(10)

NameError: name 'df' is not defined